<a href="https://colab.research.google.com/github/gudellidilipkumar/python/blob/main/Week2_1_wed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task
Analyze the provided retail store financial data to calculate net revenue, adjust revenue for inflation, and identify the most profitable store and category combination after inflation adjustment.

## Revenue matrix preparation

### Subtask:
Define the 3x3 matrix for monthly revenue per store and category.


**Reasoning**:
Define and populate the 3x3 matrix representing monthly revenue per store and category.



In [7]:
import numpy as np
import pandas as pd

# Define the stores and categories
stores = ['Store A', 'Store B', 'Store C']
categories = ['Electronics', 'Apparel', 'Groceries']

# Create a 3x3 matrix with example revenue values
revenue_matrix = np.array([
    [15000, 8000, 12000],  # Store A: Electronics, Apparel, Groceries
    [20000, 10000, 15000], # Store B: Electronics, Apparel, Groceries
    [18000, 9000, 13000]   # Store C: Electronics, Apparel, Groceries
])

# Display the matrix for verification (optional)
revenue_df = pd.DataFrame(revenue_matrix, index=stores, columns=categories)
display(revenue_df)

Electronics  Apparel  Groceries
Store A        15000     8000      12000
Store B        20000    10000      15000
Store C        18000     9000      13000

## Expenses matrix preparation

### Subtask:
Define the 3x3 matrix for monthly operational expenses per store and category.


**Reasoning**:
Create the expenses matrix and DataFrame using the provided instructions.



In [2]:
# Create a 3x3 NumPy array named expenses_matrix with example operational expense values
expenses_matrix = np.array([
    [5000, 2000, 3000],  # Store A: Electronics, Apparel, Groceries
    [6000, 2500, 3500], # Store B: Electronics, Apparel, Groceries
    [5500, 2200, 3200]   # Store C: Electronics, Apparel, Groceries
])

# Create a pandas DataFrame named expenses_df from the expenses_matrix
expenses_df = pd.DataFrame(expenses_matrix, index=stores, columns=categories)

# Display the expenses_df DataFrame to verify the created matrix
display(expenses_df)

Electronics  Apparel  Groceries
Store A         5000     2000       3000
Store B         6000     2500       3500
Store C         5500     2200       3200

## Calculate net revenue

### Subtask:
Compute the net revenue matrix by subtracting expenses from revenue.


**Reasoning**:
Subtract the expenses DataFrame from the revenue DataFrame to calculate the net revenue and store it in a new DataFrame, then display the result.



In [3]:
net_revenue_df = revenue_df - expenses_df
display(net_revenue_df)

Electronics  Apparel  Groceries
Store A        10000     6000       9000
Store B        14000     7500      11500
Store C        12500     6800       9800

## Adjust for inflation

### Subtask:
Apply an 8% inflation factor to the revenue matrix.


**Reasoning**:
Apply the inflation rate to the revenue data by creating an inflation rate variable and then multiplying the revenue DataFrame by the inverse of the inflation factor.



In [4]:
inflation_rate = 0.08
adjusted_revenue_df = revenue_df * (1 - inflation_rate)
display(adjusted_revenue_df)

Electronics  Apparel  Groceries
Store A      13800.0   7360.0    11040.0
Store B      18400.0   9200.0    13800.0
Store C      16560.0   8280.0    11960.0

## Transpose the adjusted matrix

### Subtask:
Transpose the inflation-adjusted revenue matrix.


**Reasoning**:
Transpose the adjusted revenue DataFrame and display it.



In [5]:
adjusted_revenue_transposed_df = adjusted_revenue_df.T
display(adjusted_revenue_transposed_df)

Store A  Store B  Store C
Electronics  13800.0  18400.0  16560.0
Apparel       7360.0   9200.0   8280.0
Groceries    11040.0  13800.0  11960.0

## Interpret the results

### Subtask:
Analyze the transposed matrix to identify the best-performing store and category combination and determine the most profitable store overall.


**Reasoning**:
Analyze the transposed adjusted revenue DataFrame to find the best-performing store-category combination and the most profitable store overall.



In [6]:
# Identify the cell with the highest value in adjusted_revenue_transposed_df
max_value = adjusted_revenue_transposed_df.max().max()
max_location = adjusted_revenue_transposed_df.stack().idxmax()

# Calculate the sum of adjusted revenue for each store (row sums in adjusted_revenue_transposed_df)
store_totals = adjusted_revenue_transposed_df.sum(axis=0)

# Identify the most profitable store overall
most_profitable_store = store_totals.idxmax()
most_profitable_store_revenue = store_totals.max()

print(f"Best performing store and category combination after inflation: {max_location} with adjusted revenue of {max_value:.2f}")
print(f"Most profitable store overall after inflation: {most_profitable_store} with total adjusted revenue of {most_profitable_store_revenue:.2f}")

Best performing store and category combination after inflation: ('Electronics', 'Store B') with adjusted revenue of 18400.00
Most profitable store overall after inflation: Store B with total adjusted revenue of 41400.00


## Summary:

### Data Analysis Key Findings

*   The net revenue matrix was calculated by subtracting the expenses matrix from the revenue matrix.
*   An 8% inflation rate was applied to the revenue matrix, resulting in an adjusted revenue matrix.
*   The highest adjusted revenue for a store and category combination was \$18,400.00, found in the Electronics category for Store B.
*   Store B was the most profitable store overall after adjusting for inflation, with a total adjusted revenue of \$41,400.00.

### Insights or Next Steps

*   Focus on the Electronics category in Store B to maximize profitability.
*   Investigate the performance of other store and category combinations to identify areas for improvement or potential divestment.
